# Algortihm Parameters
alpha: 0.1
gamma: 0.8
epsilon: 0.9
epsilon_discount: 0.999 # 1098 eps to reach 0.1
nepisodes: 10000
nsteps: 1000

# Input type
control_type: traj_pos #traj_vel or vel or pos or traj_pos

# Environment Parameters
desired_pose:
    x: 0.0
    y: 0.0
    z: 1.0

max_height: 3.0   # in meters
min_height: 0.0   # in meters
running_step: 0.0010   # in seconds

observations: # Observations you want to use for the learning
  - shp_joint_ang
  - shl_joint_ang
  - elb_joint_ang
  - wr1_joint_ang
  - wr2_joint_ang
  - wr3_joint_ang
  - shp_joint_vel
  - shl_joint_vel
  - elb_joint_vel
  - wr1_joint_vel
  - wr2_joint_vel
  - wr3_joint_vel
  - eef_x
  - eef_y
  - eef_z

joint_names: ['shoulder_link', 'upper_arm_link', 'forearm_link', 'wrist_1_link', 'wrist_2_link', 'wrist_3_link']

init_joint_pose:
  shp: 1.09
  shl: -1.96
  elb: 2.28
  wr1: -0.33
  wr2: 1.06
  wr3: -1.57

joint_limits_array:
  shp_max: 3.14
  shp_min: -3.14
  shl_max: 3.14
  shl_min: -3.14
  elb_max: 3.14
  elb_min: -3.14
  wr1_max: 3.14
  wr1_min: -3.14
  wr2_max: 3.14
  wr2_min: -3.14
  wr3_max: 3.14
  wr3_min: -3.14


joint_velocity_limits_array:
  shp_max: 1.0
  shp_min: -1.0
  shl_max: 1.0
  shl_min: -1.0
  elb_max: 1.0
  elb_min: -1.0
  wr1_max: 1.0
  wr1_min: -1.0
  wr2_max: 1.0
  wr2_min: -1.0
  wr3_max: 1.0
  wr3_min: -1.0


#cartesian_limits:
#  x_max: 1.0
#  x_min: 1.0
#  y_max: -1.0
#  y_min: -1.0
#  z_max: -1.0
#  z_min: -1.0

episode_done_criteria:
  - panel_10deg

  #- minimum_height
  #- monoped_vertical_orientation
