controller_list:
  - name: "pos_traj_controller" #"vel_traj_controller" or "pos_traj_controller"
#  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: "gripper_controller"
#    action_ns: gripper_action
#    type: GripperCommand
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
#    parallel: true
    joints:
      - simple_gripper_right_driver_joint
      - simple_gripper_left_driver_joint
      - simple_gripper_right_follower_joint
      - simple_gripper_left_follower_joint
      - simple_gripper_right_spring_link_joint
      - simple_gripper_left_spring_link_joint

