controller_list:
  - name: fake_manipulator_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_endeffector_controller
    joints:
      []
  - name: fake_gripper_controller
    joints:
      - simple_gripper_right_driver_joint
      - simple_gripper_left_driver_joint
      - simple_gripper_right_follower_joint
      - simple_gripper_left_follower_joint
      - simple_gripper_right_spring_link_joint
      - simple_gripper_left_spring_link_joint
